
# Config file for automatic testing at travis-ci.org
install:
  - pip install pytest-cov hypothesis
  - pip install -r requirements_dev.txt
  - pip install -e .

language: python
cache: pip
python:
  - 3.6

script:
  - pytest

