
# Config file for automatic testing at travis-ci.org
install:
  - pip install pytest-cov
  - pip install -r requirements.txt
  - pip install -e .

language: python
cache: pip
python:
  - 3.6
  - 3.5
  - 3.4

script:
  - pytest

